### ISSUE TITLE
请问有计划翻译 Building a JIT 吗？

### ISSUE THREAD

**Issue by darionyaphet** [hunterzju/llvm-tutorial#8]
您好，请问有计划翻译 Building a JIT 吗？谢谢

**Comment by hunterzju** [comment]
> 您好，请问有计划翻译 Building a JIT 吗？谢谢

感谢您的关注和PR，我目前主要在看MLIR教程；Building a JIT这部分暂时先把原始文档copy过来了，这两天会抽空出一个机器翻译的版本，但是可能暂时没有太多精力去校对。

**Comment by darionyaphet** [comment]
> 

作为一个LLVM 初学者，非常感谢您的项目，它对我的帮助很大，您能合并我的PR，我感到非常荣幸:D

不用太担心，如果可以的话，我可以逐步校对一些Building a JIT内容。

**Comment by hunterzju** [comment]
> > 
> 
> 作为一个LLVM 初学者，非常感谢您的项目，它对我的帮助很大，您能合并我的PR，我感到非常荣幸:D
> 
> 不用太担心，如果可以的话，我可以逐步校对一些Building a JIT内容。

初步机翻内容已经更新，不过这部分文档社区好像也还在完善，再次感谢您！

**Comment by darionyaphet** [comment]
👍
